# Generated by Django 4.2.6 on 2024-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_ordermedicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermedicine',
            name='bkash_number',
        ),
        migrations.AddField(
            model_name='ordermedicine',
            name='order_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='ordermedicine',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordermedicine',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='ordermedicine',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermedicine',
            name='patient_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordermedicine',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordermedicine',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
