# Generated by Django 4.2.6 on 2024-07-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_ordertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='times',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
